project:
  type: book
  output-dir: docs

book:
  title: "quantcrim"
  subtitle: "Een open-web handboek voor kwantitatief criminologisch onderzoek"
  author:
    - name: Joost Jansen
      orcid: 0000-0002-1226-2919
    - name: Malouke Kuiper
      orcid: 0000-0002-1827-7126
    - name: Gijs Custers
      orcid: 0000-0002-2716-3104
    - name: Simone Kruit
  date: last-modified
  downloads: [pdf]
  repo-url: https://github.com/joostjansen/quantcrim
  repo-actions: [source, issue]
  sidebar:
    search: true
    style: docked
    background: light

  chapters:
    - index.qmd
    - part: "Voorbereiding"
      chapters:
        - 002-setup.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    reference-location: margin
    published-title: "Updated"
    link-citations: true

  pdf:
    documentclass: scrreprt
    link-citations: true

editor: visual
