project:
  type: book
  output-dir: docs

book:
  title: "QuantCrim"
  subtitle: "Een open-web handboek voor kwantitatief onderzoek"
  author:
    - name: Joost Jansen
      orcid: 0000-0002-1226-2919
  date: last-modified
  downloads: [pdf]
  repo-url: https://github.com/joostjansen/QuantCrim
  repo-actions: [source, issue]   # also possible: [edit, issue]
  sidebar:
    search: true
    style: docked
    background: light

  chapters:
    - index.qmd
    - part: "Benodigdheden"
      chapters:
        - 002-setup.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: cosmo
      dark: darkly
  pdf:
    documentclass: scrreprt

editor: visual
